(setq edity-types '(html markdown text xml))
(setq programmy-types '(c go java javascript lisp lisp lua perl python))
(defun type->hook (type)
  (intern (concat (symbol-name type) "-mode-hook")))
(provide 'types)
